# Generated by Django 3.2.16 on 2024-10-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20241021_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
